version: '3.8'
services:

  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    image: danydodson/nginx-proxy
    volumes:
      - './nginx-proxy/data:/etc/nginx'
      - './nginx-proxy/lua:/usr/local/openresty/nginx/lua'
    networks:
      - back
      - front
    depends_on:
      - users-service

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    image: danydodson/web-client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './web-client:/usr/src/app'
      - 'web-vol:/usr/src/app/node_modules'
    stdin_open: true
    networks:
      - front
    depends_on:
      - users-service

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    image: danydodson/users-service
    volumes:
      - './users-service:/usr/src/app'
      - 'users-vol:/usr/src/app/node_modules'
    networks:
      - back

networks:
  back: null
  front: null

volumes:
  web-vol: null
  users-vol: null
