version: '3.8'
services:

  web-client:
    build: ./web-client
    image: danydodson/web-client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING:true
      - NGINX_PROXY_URL=http://nginx-proxy:8080
    volumes:
      - ./web-client:/usr/src/app
      - web-vol:/usr/src/app/node_modules
    stdin_open: true
    networks:
      - front
    depends_on:
      - nginx-proxy

  nginx-proxy:
    build: ./nginx-proxy
    restart: always
    image: danydodson/nginx-proxy
    env_file:
      - ./nginx-proxy/.env
    environment:
      - CLIENT_URL=http://web-client:3000
    volumes:
      - ./nginx-proxy/data:/etc/nginx
      - ./nginx-proxy/lua:/usr/local/openresty/nginx/lua
    networks:
      - front
      - back
    depends_on:
      - users-service

  users-service:
    build: ./users-service
    restart: always
    image: danydodson/users-service
    environment:
      - NODE_ENV=development
    volumes:
      - ./users-service:/usr/src/app
      - users-vol:/usr/src/app/node_modules
    networks:
      - back

networks:
  back: null
  front: null

volumes:
  web-vol: null
  users-vol: null
