version: '3.8'
services:

  web-client:
    build:
      target: prod
      context: ./web-client
    image: danydodson/web-client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING:true
    volumes:
      - './web-client:/usr/src/app'
      - 'web-vol:/usr/src/app/node_modules'
    stdin_open: true
    networks:
      - front
    depends_on:
      - users-service

  nginx-proxy:
    build:
      target: prod
      context: ./nginx-proxy
    restart: always
    image: danydodson/nginx-proxy
    environment:
      - NODE_ENV=development
    volumes:
      - './nginx-proxy/data:/etc/nginx'
      - './nginx-proxy/lua:/usr/local/openresty/nginx/lua'
    networks:
      - front
      - back
    depends_on:
      - users-service

  users-service:
    build: 
      target: prod
      context: ./users-service
    restart: always
    image: danydodson/users-service
    environment:
      - NODE_ENV=development
    volumes:
      - './users-service:/usr/src/app'
      - 'users-vol:/usr/src/app/node_modules'
    networks:
      - back

networks:
  back: null
  front: null

volumes:
  web-vol: null
  users-vol: null
