version: '3.8'
services:

  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: danydodson/nginx-proxy
    ports:
      - '80:8081'
    volumes:
      - './nginx-proxy/data:/etc/nginx'
      - './nginx-proxy/lua:/usr/local/openresty/nginx/lua'
    networks:
      - back-tier
    depends_on:
      - users-service

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    restart: always
    image: danydodson/users-service
    volumes:
      - './users-service:/usr/src/app'
      - 'users-nm:/usr/src/app/node_modules'
    environment:
      NODE_ENV: development
    ports:
      - 3100:3100
      - 9229:9229
    command: npm run debug
    networks:
      - back-tier

networks:
  back-tier:

volumes:
  pwa-nm: null
  web-vol: null
  users-nm: null
