version: '3.8'
services:

  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    image: danydodson/nginx-proxy
    ports:
      - 8080:8080
    volumes:
      - './nginx-proxy/data:/etc/nginx'
      - './nginx-proxy/lua:/usr/local/openresty/nginx/lua'
    networks:
      - app-net
      # - front
      # - back
    depends_on:
      - users-service

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    image: danydodson/web-client
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://0.0.0.0:8080
    stdin_open: true
    volumes:
      - './web-client:/usr/src/app'
      - 'web-vol:/usr/src/app/node_modules'
    networks:
      - app-net
      # - front
    depends_on:
      - users-service

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    image: danydodson/users-service
    volumes:
      - './users-service:/usr/src/app'
      - 'users-vol:/usr/src/app/node_modules'
    expose:
      - 3100
    networks:
      - app-net
      # - back

networks:
  app-net:
  # back: null
  # front: null

volumes:
  web-vol: null
  users-vol: null
