version: '3.8'
services:

  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    networks:
      - front
      - back
    depends_on:
      - users-service

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    networks:
      - front
    depends_on:
      - users-service

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    networks:
      - back

networks:
  front:
  back:
